# Generated by Django 2.2.6 on 2020-01-01 16:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vtrueUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('TenDN', models.CharField(max_length=100)),
                ('ngaydangky', models.DateField(auto_now_add=True)),
                ('DiaChiDangkyKD', models.CharField(max_length=200)),
                ('DienThoaiDN', models.CharField(max_length=15)),
                ('Fax', models.CharField(max_length=20)),
                ('NganhNgheKDChinh', models.CharField(max_length=255)),
                ('ThoigiandangkyKD', models.CharField(max_length=100)),
                ('DaiDienCMND', models.CharField(max_length=20)),
                ('TenNguoiDaiDien', models.CharField(max_length=50)),
                ('ChucDanh', models.CharField(blank=True, max_length=128, null=True)),
                ('EmailNguoiDaiDien', models.EmailField(max_length=128)),
                ('DienThoaiNguoiDaiDien', models.CharField(max_length=20)),
                ('TenHoSoDinhKem', models.CharField(max_length=150)),
                ('TrangThaiDuyet', models.IntegerField()),
                ('NoiCapCMND', models.CharField(blank=True, max_length=100, null=True)),
                ('NgayCapCMND', models.DateField(blank=True, null=True)),
                ('DiaChiGiaoDich', models.CharField(blank=True, max_length=200, null=True)),
                ('requeststatus', models.IntegerField(blank=True, null=True)),
                ('matinhthanh', models.CharField(blank=True, max_length=100, null=True)),
                ('quanhuyen', models.CharField(blank=True, max_length=200, null=True)),
                ('TenTK', models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('MaCapBac', models.IntegerField()),
                ('ThoiGian', models.DateTimeField()),
                ('SessionTime', models.CharField(max_length=255)),
                ('usertype', models.CharField(max_length=255)),
                ('tensohuu', models.CharField(blank=True, max_length=200, null=True)),
                ('congty_phongban', models.CharField(max_length=200)),
                ('firstLogin', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
