# Generated by Django 2.2.6 on 2020-01-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vtrueuser',
            name='_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
