# Generated by Django 2.2.6 on 2020-01-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vtrueuser__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtrueuser',
            name='DaiDienCMND',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='DiaChiDangkyKD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='DienThoaiDN',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='DienThoaiNguoiDaiDien',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='EmailNguoiDaiDien',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='Fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='MaCapBac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='NganhNgheKDChinh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='SessionTime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='TenDN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='TenHoSoDinhKem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='TenNguoiDaiDien',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='ThoiGian',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='ThoigiandangkyKD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='TrangThaiDuyet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='congty_phongban',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='ngaydangky',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='usertype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
