# Generated by Django 2.2.6 on 2020-01-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200116_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vtrueuser',
            old_name='_id',
            new_name='MaDN',
        ),
    ]
