# Generated by Django 2.2.6 on 2020-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200117_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtrueuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vtrueuser',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
