# Generated by Django 2.2.6 on 2019-12-25 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_tem', models.CharField(max_length=100)),
                ('ma_sp', models.CharField(max_length=100)),
                ('thoi_gian', models.DateField(default=datetime.date.today)),
                ('ip_adress', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('seri_number', models.CharField(max_length=100)),
            ],
        ),
    ]
