# Generated by Django 2.2.6 on 2019-12-27 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTem', models.CharField(max_length=100)),
                ('MaSP', models.CharField(max_length=100)),
                ('ThoiGian', models.DateField(default=datetime.date.today)),
                ('DiaChiIP', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=100)),
                ('SeriNo', models.CharField(max_length=100)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SMSHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTem', models.CharField(max_length=100)),
                ('MaSP', models.CharField(max_length=100)),
                ('ThoiGian', models.DateField(default=datetime.date.today)),
                ('SoDienThoai', models.CharField(max_length=100)),
                ('SeriNo', models.CharField(max_length=100)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WebHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTem', models.CharField(max_length=100)),
                ('MaSP', models.CharField(max_length=100)),
                ('ThoiGian', models.DateField(default=datetime.date.today)),
                ('DiaChiIP', models.CharField(max_length=100)),
                ('SoDienThoai', models.CharField(max_length=100)),
                ('SeriNo', models.CharField(max_length=100)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
