# Generated by Django 2.2.6 on 2020-01-02 08:23

import datetime
from django.db import migrations, models
import djongo.models.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191227_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGian', models.DateField(default=datetime.date.today)),
                ('SoDienThoai', models.CharField(max_length=100)),
                ('SeriNo', models.CharField(max_length=100)),
                ('Count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTem', models.CharField(max_length=100)),
                ('MaSP', models.CharField(max_length=100)),
                ('SMS', djongo.models.fields.EmbeddedModelField(model_container=website.models.SMSHistory, null=True)),
                ('App', djongo.models.fields.EmbeddedModelField(model_container=website.models.AppHistory, null=True)),
                ('Web', djongo.models.fields.EmbeddedModelField(model_container=website.models.WebHistory, null=True)),
                ('Call', djongo.models.fields.EmbeddedModelField(model_container=website.models.CallHistory, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sanpham',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaSP', models.CharField(max_length=100)),
                ('TenSP', models.CharField(max_length=100)),
                ('NhaSX', models.CharField(max_length=100)),
                ('LoaiSP', models.CharField(max_length=100)),
                ('LoaiHang', models.IntegerField(default=0)),
                ('NgayTao', models.DateField(default=datetime.date.today)),
                ('LoaiHinhDN', models.CharField(max_length=100)),
                ('MaCapPhep', models.CharField(max_length=100)),
                ('GiayPhep', models.CharField(max_length=100)),
                ('NgayCap', models.CharField(max_length=100)),
                ('CapBoi', models.CharField(max_length=100)),
                ('XuatXuSP', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SPofDN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaDN', models.CharField(max_length=100)),
                ('SanPham', djongo.models.fields.EmbeddedModelField(model_container=website.models.sanpham, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='apphistory',
            name='MaSP',
        ),
        migrations.RemoveField(
            model_name='apphistory',
            name='MaTem',
        ),
        migrations.RemoveField(
            model_name='smshistory',
            name='MaSP',
        ),
        migrations.RemoveField(
            model_name='smshistory',
            name='MaTem',
        ),
        migrations.RemoveField(
            model_name='webhistory',
            name='MaSP',
        ),
        migrations.RemoveField(
            model_name='webhistory',
            name='MaTem',
        ),
    ]
