# Generated by Django 2.2.6 on 2020-01-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200102_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='khotemact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaTem', models.CharField(max_length=30)),
                ('MaDL', models.CharField(max_length=30)),
                ('Serino', models.CharField(max_length=100)),
                ('MaSP', models.CharField(max_length=100)),
                ('NgayKichHoat', models.DateTimeField()),
                ('SeriTem', models.CharField(max_length=100)),
            ],
        ),
    ]
