# Generated by Django 2.2.6 on 2020-01-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200112_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='thamso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxcount', models.IntegerField(blank=True, default=4, null=True)),
            ],
        ),
    ]
