# Generated by Django 2.2.6 on 2020-01-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_thamso'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagefile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('ngaydang', models.DateField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
        ),
    ]
