# Generated by Django 2.2.6 on 2020-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200124_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='chuthich',
            field=models.TextField(default=' '),
        ),
    ]
